spring:
  cloud:
    gateway:
      routes:
        - id: announcenment_route
          uri: lb://thesis-announcement
          predicates:
            - Path=/announcement/**

        - id: document_route
          uri: lb://thesis-document
          predicates:
            - Path=/document/**

        - id: thesis-route
          uri: lb://thesis-thesis
          predicates:
            - Path=/thesis/**

        - id: third_party_route
          uri: lb://thesis-third-party
          predicates:
            - Path=/thesis-third-party/**

        - id: sys_route
          uri: lb://thesis-sys
          predicates:
            - Path=/**

#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

