spring:
  cloud:
    gateway:
      routes:
        - id: announcenment-route
          uri: lb://thesis-announcement
          predicates:
            - Path=/announcement/**

        - id: thesis-route
          uri: lb://thesis-thesis
          predicates:
            - Path=/thesis/**

        - id: third-party-route
          uri: lb://thesis-third-party
          predicates:
            - Path=/third-party/**
          filters:
            - RewritePath=/third-party/(?<segment>.*),/$\{segment}

        - id: sys_route
          uri: lb://thesis-sys
          predicates:
            - Path=/**

#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

